name: Repack GDAL Conda to WHL

on:
  push:
    branches:
      - main

jobs:
  repack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.10

    - name: Install GDAL Conda package
      run: conda install -c conda-forge gdal-3.9.0

    - name: Convert Conda package to WHL
      run: |
        conda install -c conda-forge conda-pack
        mkdir -p gdal_package
        cd gdal_package
        conda pack -n base -o gdal-3.9.0.tar.gz
        tar -xzf gdal-3.9.0.tar.gz
        pip install wheel
        python setup.py bdist_wheel

    - name: Upload WHL to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gdal-3.9.0
        path: dist/*.whl
